language: go

go:
  - "1.5.1"

env:
  global:
    - SSH_KEY="travis_key"
    - GIT_NAME="Faissal Elamraoui"
    - GIT_EMAIL="amr.faissal@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="source"

before_install:
  - openssl aes-256-cbc -K $encrypted_7030049e4c12_key -iv $encrypted_7030049e4c12_iv -in travis_key.enc -out travis_key -d

before_script:
  - git fetch
  - go get -u -v github.com/spf13/hugo

script:
  - git clone https://github.com/amrfaissal/hugo-uno ./themes/hugo-uno
  - hugo

after_success:
  - ./scripts/deploy.sh
