language: go

go:
  - "1.5.1"

env:
  global:
    - SSH_KEY="travis_key"
    - GIT_DEPLOY_USERNAME="Faissal Elamraoui"
    - GIT_DEPLOY_EMAIL="amr.faissal@gmail.com"
    - GIT_DEPLOY_DIR="public"
    - GIT_DEPLOY_BRANCH="master"

branches:
  only:
    - source

before_install:
  - openssl aes-256-cbc -K $encrypted_7030049e4c12_key -iv $encrypted_7030049e4c12_iv -in travis_key.enc -out travis_key -d

install:
  - rm -rf public || exit 0 # cleanup previous run

before_script:
  - go get -u -v github.com/spf13/hugo

script:
  - hugo

after_success:
  - cp .travis.yml public # all branches need this file
  - bash deploy.sh # run the deploy script
